package com.healthcare.room.enums;

public enum RoomType {
    PATIENT_ROOM, ICU, OPERATION_ROOM, EMERGENCY, WARD, PRIVATE, SEMI_PRIVATE, EXAMINATION_ROOM, RECOVERY_ROOM,
    STORAGE_ROOM, UTILITY_ROOM, OFFICE, MEETING_ROOM, LABORATORY, PHARMACY, KITCHEN, LAUNDRY
}

